//! Rendering the node registry to `docs/generated/CATALOG.md` (doc 14
//! §Documentation pipeline): one line per registered node — signature plus
//! title line — grouped by category, then by sub-group within it (v0.1
//! wave 5, C2c: `spec::SUBGROUPS` order, unlisted sub-groups after).
//! Committed and CI-checked fresh, like a lockfile. Agents read this
//! instead of grepping crates.

use core::fmt::Write as _;

use crate::spec::{NodeSpec, subgroup_rank};

/// Canonical category order, matching docs/08 §Catalog section order.
/// Categories not listed here render after these, alphabetically.
pub const CATEGORY_ORDER: &[&str] = &[
    "Params & input",
    "Sequences & random",
    "Maths & logic",
    "List & axis",
    "Point · Vector · Plane",
    "Curve",
    "Surface & solid",
    "Mesh & field",
    "Intersect & regions",
    "Transform",
    "Output, display & export",
];

/// Sort rank for a category: docs/08 position, unknowns after (then sorted
/// by name via the second tuple slot).
#[must_use]
pub fn category_rank(category: &'static str) -> (usize, &'static str) {
    CATEGORY_ORDER
        .iter()
        .position(|known| *known == category)
        .map_or((CATEGORY_ORDER.len(), category), |i| (i, ""))
}

/// Render the full catalog document from registered specs (pre-sorted by
/// [`crate::spec::registered`]).
///
/// Deterministic: given the same specs in the same order, the output is
/// byte-identical (the freshness CI check depends on this).
#[must_use]
pub fn render_markdown(specs: &[&NodeSpec]) -> String {
    let mut out = String::from(
        "# Node catalog\n\
         \n\
         <!-- Generated by `cicada catalog`. Do not edit by hand; CI fails when stale. -->\n\
         \n\
         One line per registered node: `signature` — Title · GH: the Grasshopper\n\
         component it replaces (absent for Cicada-only nodes) — description, plus the\n\
         node's runtime contract (its `# Panics` conditions — when it goes red) where\n\
         one exists. Nodes are grouped by category (`##`, the menu bar's tabs) and,\n\
         within it, by sub-group (`###`, the tab's columns — `#[node(sub = …)]`, the\n\
         table `cicada_core::spec::SUBGROUPS` that docs/08 §Catalog mirrors), then by\n\
         name. Type variables: `T` = any transformable kind (kind-preserving),\n\
         `E` = any element kind, optionality included (an `E` port takes absent slots;\n\
         the `?` rides through to `E` outputs — except through an `E?` port, which keeps\n\
         the `?` itself, so `compact` returns a present `[E]`), `Any` = display-sink\n\
         catch-all. `· volatile` = never memoized (recomputes every generation);\n\
         `· transport-driven` names a port the app's transport fills from the playhead\n\
         (hidden on the canvas; in the text, and headless, the kwarg is just a value).\n\
         Port docs (every input and output — the bare `out` carries the node's\n\
         `# Returns` line) and runnable examples live in `catalog.json` (`examples`:\n\
         one `.cic` snippet per node, solved by CI).\n",
    );

    let mut categories: Vec<&'static str> = Vec::new();
    for spec in specs {
        if !categories.contains(&spec.category) {
            categories.push(spec.category);
        }
    }
    // One ordering rule, shared with registered(): category_rank.
    categories.sort_by_key(|category| category_rank(category));

    for category in categories {
        // write! to a String is infallible; the discarded Result is fmt noise.
        let _ = write!(out, "\n## {category}\n");
        // The category's sub-groups as its nodes name them, in table order
        // (unlisted ones after, alphabetically) — the same rule the menu
        // bar's columns follow. A sub-group with no node here has no
        // heading: the document lists what exists.
        let mut subgroups: Vec<&'static str> = Vec::new();
        for spec in specs.iter().filter(|spec| spec.category == category) {
            if !subgroups.contains(&spec.sub) {
                subgroups.push(spec.sub);
            }
        }
        subgroups.sort_by_key(|sub| subgroup_rank(category, sub));
        for sub in subgroups {
            let _ = write!(out, "\n### {sub}\n\n");
            for spec in specs
                .iter()
                .filter(|spec| spec.category == category && spec.sub == sub)
            {
                node_line(&mut out, spec);
            }
        }
    }
    out
}

/// One node's line: signature, title, the `· GH:` / `· volatile` /
/// `· transport-driven` tags, the description, the red-when contract.
fn node_line(out: &mut String, spec: &NodeSpec) {
    let _ = write!(out, "- `{}` — {}", spec.signature(), spec.title);
    if let Some(gh) = spec.gh {
        let _ = write!(out, " · GH: {gh}");
    }
    if spec.volatile {
        // Uncached by design (docs/12 §Volatile nodes): an agent must know
        // a node recomputes every generation before wiring a heavy cone
        // behind it.
        out.push_str(" · volatile");
    }
    for port in spec.inputs {
        // The transport owns this port in the app (hidden on the canvas,
        // filled from the playhead): an agent writing the text must know
        // the kwarg is the headless value only.
        if let Some(signal) = port.transport_driven {
            let _ = write!(
                out,
                " · transport-driven `{}` ({})",
                port.name,
                signal.as_str()
            );
        }
    }
    let _ = write!(out, " — {}", spec.description);
    if let Some(panics) = spec.panics {
        let _ = write!(out, " Red when: {panics}");
    }
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spec::{PortSpec, PortType, Tier};

    static OUT_NUMBER: &[PortSpec] = &[PortSpec {
        name: "out",
        ty: PortType::named("Number"),
        default: None,
        doc: "",
        dimension: None,
        transport_driven: None,
    }];

    const fn spec(name: &'static str, title: &'static str, category: &'static str) -> NodeSpec {
        NodeSpec {
            name,
            title,
            description: "Test node.",
            category,
            sub: "Util",
            tier: Tier::S,
            version: 1,
            pure: true,
            volatile: false,
            uses_tolerance: false,
            panics: None,
            gh: None,
            examples: &[],
            inputs: &[],
            outputs: OUT_NUMBER,
            module: "test",
            line: 0,
        }
    }

    // Note: the DIALECT name has no underscore even when the Rust fn needs
    // one to dodge a keyword (`fn move_` registers as `move` — docs/10).
    static TRANSFORM_NODE: NodeSpec = spec("move", "Move", "Transform");
    static MATHS_NODE: NodeSpec = spec("add", "Add", "Maths & logic");
    static UNKNOWN_NODE: NodeSpec = spec("mystery", "Mystery", "Zebra category");

    #[test]
    fn categories_follow_docs08_order_with_unknowns_last() {
        let rendered = render_markdown(&[&TRANSFORM_NODE, &UNKNOWN_NODE, &MATHS_NODE]);
        let maths = rendered.find("## Maths & logic").unwrap();
        let transform = rendered.find("## Transform").unwrap();
        let unknown = rendered.find("## Zebra category").unwrap();
        assert!(maths < transform && transform < unknown);
    }

    #[test]
    fn node_line_is_signature_title_description() {
        let rendered = render_markdown(&[&MATHS_NODE]);
        assert!(rendered.contains("- `add() → Number` — Add — Test node.\n"));
    }

    // A category's rows sit under `###` sub-group headings in the table's
    // order (v0.1 wave 5, C2c) — Operators before Util before Logic however
    // the specs arrive — and a sub-group the table does not list trails the
    // listed ones; a listed sub-group with no node gets no heading.
    #[test]
    fn a_category_groups_its_rows_by_sub_group_in_table_order() {
        static LOGIC: NodeSpec = NodeSpec {
            sub: "Logic",
            ..spec("and", "And", "Maths & logic")
        };
        static OPERATOR: NodeSpec = NodeSpec {
            sub: "Operators",
            ..spec("add", "Add", "Maths & logic")
        };
        static UNLISTED: NodeSpec = NodeSpec {
            sub: "Anything",
            ..spec("odd", "Odd", "Maths & logic")
        };
        // `MATHS_NODE` is `Util`; `TRANSFORM_NODE` is another category.
        let rendered =
            render_markdown(&[&UNLISTED, &LOGIC, &MATHS_NODE, &OPERATOR, &TRANSFORM_NODE]);
        let heading = |text: &str| {
            rendered
                .find(text)
                .unwrap_or_else(|| panic!("`{text}` in:\n{rendered}"))
        };
        let maths = heading("## Maths & logic");
        let operators = heading("### Operators");
        let util = heading("### Util");
        let logic = heading("### Logic");
        let anything = heading("### Anything");
        let transform = heading("## Transform");
        assert!(maths < operators && operators < util && util < logic && logic < anything);
        assert!(
            anything < transform,
            "the unlisted sub-group stays in its category"
        );
        assert!(
            !rendered.contains("### Trig"),
            "no heading for an empty sub-group"
        );
        // Each row is under its own heading.
        let add = heading("- `add()");
        let and = heading("- `and()");
        assert!(operators < add && add < util && logic < and && and < anything);
        // One `###` per sub-group present, the category's `Util` heading
        // shared by nothing else (the Transform `move` is under its own).
        assert_eq!(rendered.matches("### Util").count(), 2, "{rendered}");
    }

    // The GH name sits between the title and the description so a migrant
    // scanning the catalog finds the component they know next to ours.
    #[test]
    fn node_line_carries_the_gh_name_after_the_title() {
        static WITH_GH: NodeSpec = NodeSpec {
            gh: Some("Addition"),
            ..spec("add", "Add", "Maths & logic")
        };
        let rendered = render_markdown(&[&WITH_GH]);
        assert!(
            rendered.contains("- `add() → Number` — Add · GH: Addition — Test node.\n"),
            "{rendered}"
        );
    }

    #[test]
    fn node_line_tags_volatile_nodes() {
        static VOLATILE: NodeSpec = NodeSpec {
            volatile: true,
            ..spec("clock", "Clock", "Params & input")
        };
        let rendered = render_markdown(&[&VOLATILE]);
        assert!(
            rendered.contains(
                "- `clock() → Number` — Clock · volatile — Test node.
"
            ),
            "{rendered}"
        );
        // The tag never appears on an ordinary node's line (the header
        // explains it, so look at the line).
        assert!(!node_line(&render_markdown(&[&MATHS_NODE])).contains("volatile"));
    }

    /// The one node line of a single-node rendering.
    fn node_line(rendered: &str) -> &str {
        rendered
            .lines()
            .find(|line| line.starts_with("- `"))
            .expect("a node line")
    }

    // A transport-driven port is named on the line with its signal: an
    // agent writing the text learns the kwarg is the headless value only.
    #[test]
    fn node_line_names_transport_driven_ports() {
        static FRAME_IN: &[PortSpec] = &[PortSpec {
            name: "frame",
            ty: PortType::named("Integer"),
            default: Some("0"),
            doc: "",
            dimension: None,
            transport_driven: Some(crate::spec::TransportSignal::Frame),
        }];
        static DRIVEN: NodeSpec = NodeSpec {
            inputs: FRAME_IN,
            ..spec("cycle", "Cycle", "Params & input")
        };
        let rendered = render_markdown(&[&DRIVEN]);
        assert!(
            rendered.contains(
                "- `cycle(frame: Integer = 0) → Number` — Cycle · transport-driven `frame` \
                 (frame) — Test node.\n"
            ),
            "{rendered}"
        );
        assert!(!node_line(&render_markdown(&[&MATHS_NODE])).contains("transport-driven"));
    }

    #[test]
    fn category_rank_orders_known_before_unknown() {
        assert!(category_rank("Maths & logic") < category_rank("Transform"));
        assert!(category_rank("Transform") < category_rank("Zebra category"));
        assert!(category_rank("Alpha unknown") < category_rank("Zebra category"));
    }

    #[test]
    fn rendering_is_deterministic() {
        let a = render_markdown(&[&TRANSFORM_NODE, &MATHS_NODE]);
        let b = render_markdown(&[&TRANSFORM_NODE, &MATHS_NODE]);
        assert_eq!(a, b);
    }
}
