//! Rendering the node registry to `docs/generated/CATALOG.md` (doc 14
//! §Documentation pipeline): one line per registered node — signature plus
//! title line — grouped by category. Committed and CI-checked fresh, like a
//! lockfile. Agents read this instead of grepping crates.

use core::fmt::Write as _;

use crate::spec::NodeSpec;

/// Canonical category order, matching docs/08 §Catalog section order.
/// Categories not listed here render after these, alphabetically.
pub const CATEGORY_ORDER: &[&str] = &[
    "Params & input",
    "Sequences & random",
    "Maths & logic",
    "List & axis",
    "Point · Vector · Plane",
    "Curve",
    "Surface & solid",
    "Mesh & field",
    "Intersect & regions",
    "Transform",
    "Output, display & export",
];

/// Sort rank for a category: docs/08 position, unknowns after (then sorted
/// by name via the second tuple slot).
#[must_use]
pub fn category_rank(category: &'static str) -> (usize, &'static str) {
    CATEGORY_ORDER
        .iter()
        .position(|known| *known == category)
        .map_or((CATEGORY_ORDER.len(), category), |i| (i, ""))
}

/// Render the full catalog document from registered specs (pre-sorted by
/// [`crate::spec::registered`]).
///
/// Deterministic: given the same specs in the same order, the output is
/// byte-identical (the freshness CI check depends on this).
#[must_use]
pub fn render_markdown(specs: &[&NodeSpec]) -> String {
    let mut out = String::from(
        "# Node catalog\n\
         \n\
         <!-- Generated by `cicada catalog`. Do not edit by hand; CI fails when stale. -->\n\
         \n\
         One line per registered node: `signature` — Title · GH: the Grasshopper\n\
         component it replaces (absent for Cicada-only nodes) — description, plus the\n\
         node's runtime contract (its `# Panics` conditions — when it goes red) where\n\
         one exists. Type variables: `T` = any transformable kind (kind-preserving),\n\
         `E` = any element kind, optionality included (an `E` port takes absent slots;\n\
         the `?` rides through to `E` outputs), `Any` = display-sink catch-all.\n\
         Port docs (every input and output — the bare `out` carries the node's\n\
         `# Returns` line) and runnable examples live in `catalog.json` (`examples`:\n\
         one `.cic` snippet per node, solved by CI).\n",
    );

    let mut categories: Vec<&'static str> = Vec::new();
    for spec in specs {
        if !categories.contains(&spec.category) {
            categories.push(spec.category);
        }
    }
    // One ordering rule, shared with registered(): category_rank.
    categories.sort_by_key(|category| category_rank(category));

    for category in categories {
        // write! to a String is infallible; the discarded Result is fmt noise.
        let _ = write!(out, "\n## {category}\n\n");
        for spec in specs.iter().filter(|spec| spec.category == category) {
            let _ = write!(out, "- `{}` — {}", spec.signature(), spec.title);
            if let Some(gh) = spec.gh {
                let _ = write!(out, " · GH: {gh}");
            }
            if spec.volatile {
                // Uncached by design (docs/12 §Volatile nodes): an agent
                // must know a node recomputes every generation before
                // wiring a heavy cone behind it.
                out.push_str(" · volatile");
            }
            let _ = write!(out, " — {}", spec.description);
            if let Some(panics) = spec.panics {
                let _ = write!(out, " Red when: {panics}");
            }
            out.push('\n');
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spec::{PortSpec, PortType, Tier};

    static OUT_NUMBER: &[PortSpec] = &[PortSpec {
        name: "out",
        ty: PortType::named("Number"),
        default: None,
        doc: "",
        dimension: None,
    }];

    const fn spec(name: &'static str, title: &'static str, category: &'static str) -> NodeSpec {
        NodeSpec {
            name,
            title,
            description: "Test node.",
            category,
            tier: Tier::S,
            version: 1,
            pure: true,
            volatile: false,
            uses_tolerance: false,
            panics: None,
            gh: None,
            examples: &[],
            inputs: &[],
            outputs: OUT_NUMBER,
            module: "test",
            line: 0,
        }
    }

    // Note: the DIALECT name has no underscore even when the Rust fn needs
    // one to dodge a keyword (`fn move_` registers as `move` — docs/10).
    static TRANSFORM_NODE: NodeSpec = spec("move", "Move", "Transform");
    static MATHS_NODE: NodeSpec = spec("add", "Add", "Maths & logic");
    static UNKNOWN_NODE: NodeSpec = spec("mystery", "Mystery", "Zebra category");

    #[test]
    fn categories_follow_docs08_order_with_unknowns_last() {
        let rendered = render_markdown(&[&TRANSFORM_NODE, &UNKNOWN_NODE, &MATHS_NODE]);
        let maths = rendered.find("## Maths & logic").unwrap();
        let transform = rendered.find("## Transform").unwrap();
        let unknown = rendered.find("## Zebra category").unwrap();
        assert!(maths < transform && transform < unknown);
    }

    #[test]
    fn node_line_is_signature_title_description() {
        let rendered = render_markdown(&[&MATHS_NODE]);
        assert!(rendered.contains("- `add() → Number` — Add — Test node.\n"));
    }

    // The GH name sits between the title and the description so a migrant
    // scanning the catalog finds the component they know next to ours.
    #[test]
    fn node_line_carries_the_gh_name_after_the_title() {
        static WITH_GH: NodeSpec = NodeSpec {
            gh: Some("Addition"),
            ..spec("add", "Add", "Maths & logic")
        };
        let rendered = render_markdown(&[&WITH_GH]);
        assert!(
            rendered.contains("- `add() → Number` — Add · GH: Addition — Test node.\n"),
            "{rendered}"
        );
    }

    #[test]
    fn node_line_tags_volatile_nodes() {
        static VOLATILE: NodeSpec = NodeSpec {
            volatile: true,
            ..spec("clock", "Clock", "Params & input")
        };
        let rendered = render_markdown(&[&VOLATILE]);
        assert!(
            rendered.contains(
                "- `clock() → Number` — Clock · volatile — Test node.
"
            ),
            "{rendered}"
        );
        // Nothing shipped is volatile yet: the tag never appears otherwise.
        assert!(!render_markdown(&[&MATHS_NODE]).contains("volatile"));
    }

    #[test]
    fn category_rank_orders_known_before_unknown() {
        assert!(category_rank("Maths & logic") < category_rank("Transform"));
        assert!(category_rank("Transform") < category_rank("Zebra category"));
        assert!(category_rank("Alpha unknown") < category_rank("Zebra category"));
    }

    #[test]
    fn rendering_is_deterministic() {
        let a = render_markdown(&[&TRANSFORM_NODE, &MATHS_NODE]);
        let b = render_markdown(&[&TRANSFORM_NODE, &MATHS_NODE]);
        assert_eq!(a, b);
    }
}
