//! Rendering the node registry to `docs/generated/CATALOG.md` (doc 14
//! §Documentation pipeline): one line per registered node — signature plus
//! title line — grouped by category. Committed and CI-checked fresh, like a
//! lockfile. Agents read this instead of grepping crates.

use core::fmt::Write as _;

use crate::spec::NodeSpec;

/// Canonical category order, matching docs/08 §Catalog section order.
/// Categories not listed here render after these, alphabetically.
pub const CATEGORY_ORDER: &[&str] = &[
    "Params & input",
    "Sequences & random",
    "Maths & logic",
    "List & axis",
    "Point · Vector · Plane",
    "Curve",
    "Surface & solid",
    "Mesh & field",
    "Intersect & regions",
    "Transform",
    "Output, display & export",
];

/// Render the full catalog document from registered specs.
///
/// Deterministic: given the same specs in the same order, the output is
/// byte-identical (the freshness CI check depends on this).
#[must_use]
pub fn render_markdown(specs: &[&NodeSpec]) -> String {
    let mut out = String::from(
        "# Node catalog\n\
         \n\
         <!-- Generated by `cicada catalog`. Do not edit by hand; CI fails when stale. -->\n\
         \n\
         One line per registered node: `signature` — Title — description.\n",
    );

    let mut categories: Vec<&str> = Vec::new();
    for spec in specs {
        if !categories.contains(&spec.category) {
            categories.push(spec.category);
        }
    }
    categories.sort_by_key(|category| {
        CATEGORY_ORDER
            .iter()
            .position(|known| known == category)
            .map_or_else(|| (CATEGORY_ORDER.len(), *category), |i| (i, ""))
    });

    for category in categories {
        // write! to a String is infallible; the discarded Result is fmt noise.
        let _ = write!(out, "\n## {category}\n\n");
        for spec in specs.iter().filter(|spec| spec.category == category) {
            let _ = writeln!(
                out,
                "- `{}` — {} — {}",
                spec.signature(),
                spec.title,
                spec.description
            );
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spec::PortSpec;

    static OUT_NUMBER: &[PortSpec] = &[PortSpec {
        name: "out",
        ty: "Number",
        default: None,
    }];

    // Note: the DIALECT name has no underscore even when the Rust fn needs
    // one to dodge a keyword (`fn move_` registers as `move` — docs/10).
    static TRANSFORM_NODE: NodeSpec = NodeSpec {
        name: "move",
        title: "Move",
        description: "Translate geometry along a vector.",
        category: "Transform",
        inputs: &[],
        outputs: OUT_NUMBER,
    };
    static MATHS_NODE: NodeSpec = NodeSpec {
        name: "add",
        title: "Add",
        description: "Sum of two numbers.",
        category: "Maths & logic",
        inputs: &[],
        outputs: OUT_NUMBER,
    };
    static UNKNOWN_NODE: NodeSpec = NodeSpec {
        name: "mystery",
        title: "Mystery",
        description: "Not in any known category.",
        category: "Zebra category",
        inputs: &[],
        outputs: OUT_NUMBER,
    };

    #[test]
    fn categories_follow_docs08_order_with_unknowns_last() {
        // Registered out of order: Transform, unknown, Maths — the doc must
        // come out Maths (3) before Transform (10), unknown last.
        let rendered = render_markdown(&[&TRANSFORM_NODE, &UNKNOWN_NODE, &MATHS_NODE]);
        let maths = rendered.find("## Maths & logic").unwrap();
        let transform = rendered.find("## Transform").unwrap();
        let unknown = rendered.find("## Zebra category").unwrap();
        assert!(maths < transform && transform < unknown);
    }

    #[test]
    fn node_line_is_signature_title_description() {
        let rendered = render_markdown(&[&MATHS_NODE]);
        assert!(rendered.contains("- `add() → Number` — Add — Sum of two numbers.\n"));
    }

    #[test]
    fn rendering_is_deterministic() {
        let a = render_markdown(&[&TRANSFORM_NODE, &MATHS_NODE]);
        let b = render_markdown(&[&TRANSFORM_NODE, &MATHS_NODE]);
        assert_eq!(a, b);
    }
}
